apiVersion: apps/v1
kind: Deployment
metadata:
  name: newflashapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newflashapp
  template:
    metadata:
      labels:
        app: newflashapp
    spec:
      containers:
      - name: flask-container
        image: mydocker3692/newflashapp:latest
        ports:
        - containerPort: 5000
