apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flashapp
  template:
    metadata:
      labels:
        app: flashapp
    spec:
      containers:
      - name: flask-container
        image: mydocker3692/flashapp:latest
        ports:
        - containerPort: 5000
